dataset_class: BoxOnlyDataset
paras:
  batch_size: 2048
  data_root: ../data/kitti
  for_train: true
  num_workers: 4
  screen_no_dt: true
#  resample_by: x
  discretize: True
  # average: segments has same length
  # balance: segments has same samples
  discretize_type: average